# Generated by Django 5.2.5 on 2025-09-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_dateprod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatut', models.CharField(max_length=150)),
            ],
        ),
    ]
