# Generated by Django 4.2.24 on 2025-09-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statutprod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('refProd', 'idRayon')},
        ),
    ]
